# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/sprout/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/google/sprout/proprietary/vendor/bin/6620_launcher:$(TARGET_COPY_OUT_VENDOR)/bin/6620_launcher \
    vendor/google/sprout/proprietary/vendor/bin/bmc156d:$(TARGET_COPY_OUT_VENDOR)/bin/bmc156d \
    vendor/google/sprout/proprietary/vendor/bin/ccci_fsd:$(TARGET_COPY_OUT_VENDOR)/bin/ccci_fsd \
    vendor/google/sprout/proprietary/vendor/bin/ccci_mdinit:$(TARGET_COPY_OUT_VENDOR)/bin/ccci_mdinit \
    vendor/google/sprout/proprietary/vendor/bin/gsm0710muxd:$(TARGET_COPY_OUT_VENDOR)/bin/gsm0710muxd \
    vendor/google/sprout/proprietary/vendor/bin/lsm303md:$(TARGET_COPY_OUT_VENDOR)/bin/lsm303md \
    vendor/google/sprout/proprietary/vendor/bin/md_ctrl:$(TARGET_COPY_OUT_VENDOR)/bin/md_ctrl \
    vendor/google/sprout/proprietary/vendor/bin/msensord:$(TARGET_COPY_OUT_VENDOR)/bin/msensord \
    vendor/google/sprout/proprietary/vendor/bin/mtk_agpsd:$(TARGET_COPY_OUT_VENDOR)/bin/mtk_agpsd \
    vendor/google/sprout/proprietary/vendor/bin/muxreport:$(TARGET_COPY_OUT_VENDOR)/bin/muxreport \
    vendor/google/sprout/proprietary/vendor/bin/nvram_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_daemon \
    vendor/google/sprout/proprietary/vendor/bin/thermal_manager:$(TARGET_COPY_OUT_VENDOR)/bin/thermal_manager \
    vendor/google/sprout/proprietary/vendor/bin/wmt_loader:$(TARGET_COPY_OUT_VENDOR)/bin/wmt_loader \
    vendor/google/sprout/proprietary/vendor/etc/firmware/ROMv1_patch_1_0_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ROMv1_patch_1_0_hdr.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/ROMv1_patch_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ROMv1_patch_1_1_hdr.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/WIFI_RAM_CODE_SOC:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/WIFI_RAM_CODE_SOC \
    vendor/google/sprout/proprietary/vendor/etc/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/WMT_SOC.cfg \
    vendor/google/sprout/proprietary/vendor/etc/firmware/catcher_filter_1_wg_n.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/catcher_filter_1_wg_n.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/modem_1_wg_n.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/modem_1_wg_n.img \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    vendor/google/sprout/proprietary/vendor/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
    vendor/google/sprout/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/google/sprout/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/google/sprout/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/google/sprout/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/google/sprout/proprietary/vendor/lib/egl/libEGL_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_mali.so \
    vendor/google/sprout/proprietary/vendor/lib/egl/libGLESv1_CM_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_mali.so \
    vendor/google/sprout/proprietary/vendor/lib/egl/libGLESv2_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_mali.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/audio.primary.mt6582.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.mt6582.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/camera.mt6582.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.mt6582.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/gralloc.mt6582.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.mt6582.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/hwcomposer.mt6582.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.mt6582.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/lights.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/lights.default.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/memtrack.mt6582.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.mt6582.so \
    vendor/google/sprout/proprietary/vendor/lib/hw/radio.fm.mt6582.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/radio.fm.mt6582.so \
    vendor/google/sprout/proprietary/vendor/lib/sensors.mt6582:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.mt6582 \
    vendor/google/sprout/proprietary/vendor/lib/lib3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a.so \
    vendor/google/sprout/proprietary/vendor/lib/libJpgEncPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libJpgEncPipe.so \
    vendor/google/sprout/proprietary/vendor/lib/libMali.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMali.so \
    vendor/google/sprout/proprietary/vendor/lib/libMtkOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxCore.so \
    vendor/google/sprout/proprietary/vendor/lib/libMtkOmxVdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVdec.so \
    vendor/google/sprout/proprietary/vendor/lib/libMtkOmxVenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVenc.so \
    vendor/google/sprout/proprietary/vendor/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilter.so \
    vendor/google/sprout/proprietary/vendor/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentengine.so \
    vendor/google/sprout/proprietary/vendor/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocustparam.so \
    vendor/google/sprout/proprietary/vendor/lib/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiodcrflt.so \
    vendor/google/sprout/proprietary/vendor/lib/libaudiomtkdcremoval.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiomtkdcremoval.so \
    vendor/google/sprout/proprietary/vendor/lib/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosetting.so \
    vendor/google/sprout/proprietary/vendor/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbessound_hd_mtk.so \
    vendor/google/sprout/proprietary/vendor/lib/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc.so \
    vendor/google/sprout/proprietary/vendor/lib/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc32.so \
    vendor/google/sprout/proprietary/vendor/lib/libbluetooth_mtk_pure.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_mtk_pure.so \
    vendor/google/sprout/proprietary/vendor/lib/libbwc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbwc.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.camadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camadapter.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.campipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.campipe.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.camshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camshot.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.device1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.device1.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.device3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.device3.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.exif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.exif.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.exif.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.exif.v3.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.hal3a.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.hal3a.v3.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.halsensor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.halsensor.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.iopipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.iopipe.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.iopipe_FrmB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.iopipe_FrmB.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.metadata.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.metadata.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.metadataprovider.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.metadataprovider.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam.paramsmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.paramsmgr.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam3_app.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_app.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam3_hwnode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_hwnode.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam3_hwpipeline.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_hwpipeline.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam3_pipeline.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_pipeline.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam3_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_utils.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam_hwutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_hwutils.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam_mmp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_mmp.so \
    vendor/google/sprout/proprietary/vendor/lib/libcam_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_platform.so \
    vendor/google/sprout/proprietary/vendor/lib/libcamalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamalgo.so \
    vendor/google/sprout/proprietary/vendor/lib/libcamdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamdrv.so \
    vendor/google/sprout/proprietary/vendor/lib/libcamdrv_FrmB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamdrv_FrmB.so \
    vendor/google/sprout/proprietary/vendor/lib/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameracustom.so \
    vendor/google/sprout/proprietary/vendor/lib/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_nvram.so \
    vendor/google/sprout/proprietary/vendor/lib/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcvsd_mtk.so \
    vendor/google/sprout/proprietary/vendor/lib/libdpframework.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdpframework.so \
    vendor/google/sprout/proprietary/vendor/lib/libdrmmtkutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmmtkutil.so \
    vendor/google/sprout/proprietary/vendor/lib/libmtkcamera_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkcamera_client.so \
    vendor/google/sprout/proprietary/vendor/lib/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfile_op.so \
    vendor/google/sprout/proprietary/vendor/lib/libfmcust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfmcust.so \
    vendor/google/sprout/proprietary/vendor/lib/libfmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfmjni.so \
    vendor/google/sprout/proprietary/vendor/lib/libhwm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwm.so \
    vendor/google/sprout/proprietary/vendor/lib/libimageio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio.so \
    vendor/google/sprout/proprietary/vendor/lib/libimageio_FrmB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio_FrmB.so \
    vendor/google/sprout/proprietary/vendor/lib/libimageio_plat_drv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio_plat_drv.so \
    vendor/google/sprout/proprietary/vendor/lib/libimageio_plat_drv_FrmB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio_plat_drv_FrmB.so \
    vendor/google/sprout/proprietary/vendor/lib/libm4u.so:$(TARGET_COPY_OUT_VENDOR)/lib/libm4u.so \
    vendor/google/sprout/proprietary/vendor/lib/libmnl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmnl.so \
    vendor/google/sprout/proprietary/vendor/lib/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmsbc_mtk.so \
    vendor/google/sprout/proprietary/vendor/lib/libmtk_drvb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_drvb.so \
    vendor/google/sprout/proprietary/vendor/lib/libmtk_mali_user.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_mali_user.so \
    vendor/google/sprout/proprietary/vendor/lib/libmtk_mmutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_mmutils.so \
    vendor/google/sprout/proprietary/vendor/lib/libmtkcamera_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkcamera_client.so \
    vendor/google/sprout/proprietary/vendor/lib/libmtkjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkjpeg.so \
    vendor/google/sprout/proprietary/vendor/lib/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_daemon_callback.so \
    vendor/google/sprout/proprietary/vendor/lib/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_platform.so \
    vendor/google/sprout/proprietary/vendor/lib/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libspeech_enh_lib.so \
    vendor/google/sprout/proprietary/vendor/lib/libssladp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssladp.so \
    vendor/google/sprout/proprietary/vendor/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so \
    vendor/google/sprout/proprietary/vendor/lib/libvcodec_utility.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_utility.so \
    vendor/google/sprout/proprietary/vendor/lib/libvcodecdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodecdrv.so \
    vendor/google/sprout/proprietary/vendor/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
    vendor/google/sprout/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L3.so \
    vendor/google/sprout/proprietary/vendor/lib/libWVphoneAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVphoneAPI.so \
    vendor/google/sprout/proprietary/vendor/vendor/lib/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libfrsdk.so \
    vendor/google/sprout/proprietary/vendor/lib/libskia.so:$(TARGET_COPY_OUT_VENDOR)/lib/libskia.so \
    vendor/google/sprout/proprietary/vendor/lib/libwvdrm_L3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L3.so \
    vendor/google/sprout/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so \
    vendor/google/sprout/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/google/sprout/proprietary/vendor/xbin/mnld:$(TARGET_COPY_OUT_VENDOR)/xbin/mnld

PRODUCT_PACKAGES += \
    libcam.utils \
    libcam1client \
    libcam_utils \
    libged \
    libion_mtk \
    libnvram \
    librilmtk \
    mtk-ril \
    FMRadioGoogle \
    FmRadioTrampoline2
